system:
  defaultLang: cn
jwt:
  expires: 1440              # token过期时长(分钟)
  refreshTokenExpires: 10080 # refresh_token的过期时长(分钟)
  secret: gin_web_secret     # 密钥
  issuer: gin_web            # issuer
  tokenKey: Authorization           # 客户端token对应的header-key
  refreshTokenKey: "Refresh-Token"    # 客户端token对应的header-key
  tokenPrefix: "Bearer "     # token前缀
logger:
  maxSize: 1     # 日志文件切割尺寸(m)
  maxBackups: 10 # 保留文件对最大个数
  maxAge: 90     # 保留文件对最大天数
  level: -1
  dir: "./log"   # 日志文件存放的目录,为空时默认在项目目录下创建log目录存放日志文件
cors:
  originPrefix:
    - http://localhost
    - http://127.0.0.1
captcha:
  keyPrefix: "captcha:"
  expiration: 60 # 秒
casbin:
  cacheExpireTime: 3600 # 秒