basePath: /api/v1
definitions:
  request.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  request.SignUpRequest:
    properties:
      code:
        type: string
      email:
        type: string
      id:
        type: string
      password:
        type: string
    required:
    - code
    - email
    - id
    - password
    type: object
  response.BasicResponse-any:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  response.BasicResponse-string:
    properties:
      code:
        type: integer
      data:
        type: string
      message:
        type: string
    type: object
info:
  contact:
    email: zhangzhouou@gmail.com
    name: Idris
    url: https://github.com/supuwoerc
  description: This is a sample server celler server.
  title: Learn-Gin-Web API
  version: "1.0"
paths:
  /api/v1/public/user/login:
    post:
      consumes:
      - application/json
      description: 用于用户登录
      parameters:
      - description: 注册参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "10000":
          description: 操作成功
          schema:
            $ref: '#/definitions/response.BasicResponse-any'
        "10001":
          description: 操作失败
          schema:
            $ref: '#/definitions/response.BasicResponse-any'
        "10002":
          description: 参数错误
          schema:
            $ref: '#/definitions/response.BasicResponse-any'
      summary: 用户登录
      tags:
      - 用户模块
  /api/v1/public/user/signup:
    post:
      consumes:
      - application/json
      description: 用于用户注册帐号
      parameters:
      - description: 注册参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.SignUpRequest'
      produces:
      - application/json
      responses:
        "10000":
          description: 操作成功
          schema:
            $ref: '#/definitions/response.BasicResponse-any'
        "10001":
          description: 操作失败
          schema:
            $ref: '#/definitions/response.BasicResponse-string'
        "10002":
          description: 参数错误
          schema:
            $ref: '#/definitions/response.BasicResponse-string'
      summary: 用户注册
      tags:
      - 用户模块
  /api/v1/user/profile:
    get:
      consumes:
      - application/json
      description: 获取用户账户信息
      produces:
      - application/json
      responses:
        "10000":
          description: 操作成功
          schema:
            $ref: '#/definitions/response.BasicResponse-any'
        "10001":
          description: 操作失败
          schema:
            $ref: '#/definitions/response.BasicResponse-any'
        "10002":
          description: 参数错误
          schema:
            $ref: '#/definitions/response.BasicResponse-any'
      summary: 用户信息
      tags:
      - 用户模块
swagger: "2.0"
