basePath: /api/v1
definitions:
  models.Permission:
    properties:
      name:
        type: string
      resource:
        type: string
      roles:
        items:
          $ref: '#/definitions/models.Role'
        type: array
    type: object
  models.Role:
    properties:
      name:
        type: string
      permissions:
        items:
          $ref: '#/definitions/models.Permission'
        type: array
      users:
        items:
          $ref: '#/definitions/models.User'
        type: array
    type: object
  models.User:
    properties:
      about:
        type: string
      birthday:
        type: string
      email:
        type: string
      gender:
        type: integer
      nickname:
        type: string
      password:
        type: string
      roles:
        items:
          $ref: '#/definitions/models.Role'
        type: array
    type: object
  request.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  request.SignUpRequest:
    properties:
      code:
        type: string
      email:
        type: string
      id:
        type: string
      password:
        type: string
    required:
    - code
    - email
    - id
    - password
    type: object
  response.BasicResponse-any:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
host: localhost:8804
info:
  contact:
    email: zhangzhouou@gmail.com
    name: Idris
    url: https://github.com/supuwoerc
  description: 基于Gin开发的项目脚手架
  title: Learn-Gin-Web API
  version: "1.0"
paths:
  /api/v1/public/user/login:
    post:
      consumes:
      - application/json
      description: 用于用户登录
      parameters:
      - description: 注册参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "10000":
          description: 操作成功
          schema:
            allOf:
            - $ref: '#/definitions/response.BasicResponse-any'
            - properties:
                data:
                  type: object
              type: object
        "10001":
          description: 操作失败
          schema:
            allOf:
            - $ref: '#/definitions/response.BasicResponse-any'
            - properties:
                data:
                  type: object
              type: object
        "10002":
          description: 参数错误
          schema:
            allOf:
            - $ref: '#/definitions/response.BasicResponse-any'
            - properties:
                data:
                  type: object
              type: object
      summary: 用户登录
      tags:
      - 用户模块
  /api/v1/public/user/signup:
    post:
      consumes:
      - application/json
      description: 用于用户注册帐号
      parameters:
      - description: 注册参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.SignUpRequest'
      produces:
      - application/json
      responses:
        "10000":
          description: 操作成功
          schema:
            allOf:
            - $ref: '#/definitions/response.BasicResponse-any'
            - properties:
                data:
                  type: object
              type: object
        "10001":
          description: 操作失败
          schema:
            allOf:
            - $ref: '#/definitions/response.BasicResponse-any'
            - properties:
                data:
                  type: object
              type: object
        "10002":
          description: 参数错误
          schema:
            allOf:
            - $ref: '#/definitions/response.BasicResponse-any'
            - properties:
                data:
                  type: object
              type: object
      summary: 用户注册
      tags:
      - 用户模块
  /api/v1/user/profile:
    get:
      consumes:
      - application/json
      description: 获取用户账户信息
      produces:
      - application/json
      responses:
        "10000":
          description: 操作成功
          schema:
            allOf:
            - $ref: '#/definitions/response.BasicResponse-any'
            - properties:
                data:
                  $ref: '#/definitions/models.User'
              type: object
        "10001":
          description: 操作失败
          schema:
            allOf:
            - $ref: '#/definitions/response.BasicResponse-any'
            - properties:
                data:
                  type: object
              type: object
        "10002":
          description: 参数错误
          schema:
            allOf:
            - $ref: '#/definitions/response.BasicResponse-any'
            - properties:
                data:
                  type: object
              type: object
      summary: 用户信息
      tags:
      - 用户模块
  /api/v1/user/set-roles:
    post:
      consumes:
      - application/json
      description: 设置用户角色
      produces:
      - application/json
      responses:
        "10000":
          description: 操作成功
          schema:
            allOf:
            - $ref: '#/definitions/response.BasicResponse-any'
            - properties:
                data:
                  type: boolean
              type: object
        "10001":
          description: 操作失败
          schema:
            allOf:
            - $ref: '#/definitions/response.BasicResponse-any'
            - properties:
                data:
                  type: object
              type: object
        "10002":
          description: 参数错误
          schema:
            allOf:
            - $ref: '#/definitions/response.BasicResponse-any'
            - properties:
                data:
                  type: object
              type: object
      summary: 用户信息
      tags:
      - 用户模块
swagger: "2.0"
