name: Deploy-Learn-Gin-Web
'on':
  push:
    branches:
      - main
jobs:
  build-GoAppliation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-Repository
        uses: actions/checkout@v4

      - name: Setup-Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'
          check-latest: false
      - run: go version

      - name: Install-Application-Dependencies
        run: go mod download

      - name: Build-Application
        run: |
          export GIN_MODE=release
          GOOS=linux go build -o build/main -v

      - name: Display-Build-Result
        run: ls -R build/

      - name: Deploy-Application-To-Ubuntu
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }
          username: ${{ secrets.REMOTE_USER }
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            mkdir -p /var/www/learn-gin-web
            mv $GITHUB_WORKSPACE/build/main var/www/learn-gin-web/main
            mv $GITHUB_WORKSPACE/run.sh var/www/learn-gin-web/run.sh
            cd /var/www/learn-gin-web
            ls -l
            ./run.sh